### PR TITLE
Fixed conflict and merged upstream/master latest changes

### PR DESCRIPTION
**Pull request by fastlorenzo**

### CODE REVIEW

**Comment by fastlorenzo** [comment]
@dchirikov I've merged the latest changes in your branch + fixed the merge conflict

**Comment by dchirikov** [comment]
Looks good, but I have some doubts if we merge this, GitHub will chew the one to upstream:
https://github.com/rancher/local-path-provisioner/pull/183

**Comment by dchirikov** [comment]
Checked more carefully. Looks like this PR reintroduced https://github.com/rancher/local-path-provisioner/issues/186
I think I'll close this PR and rebase mine to the upstream in order not to turn `git log --graph` into guitar hero.

**Comment by fastlorenzo** [comment]
yep, sounds like a better plan 😄 
I've tried to do a rebase initially, but as I don't have write access to your branch I could not force push it

**Pull request closed without merging**
